### ISSUE TITLE
Use gender neutral language/placeholder info

### ISSUE THREAD

**Issue by sarahemm** [hacklabto/membership-application-webapp#10]
Currently we're using gendered placeholder info, should fix this.

**Comment by f3ndot** [comment]
True. I originally tried to balance it with Ada Lovelace and Alan Turing, but those no longer exist :wink: 

Let's go with "Sparky" or something like that instead of John Smith-based placeholders

**Comment by f3ndot** [comment]
Or, better yet:

Real Name: `First Last`
Username: `flast`
Nickname: `Firsty`

**Comment by f3ndot** [comment]
I'm trying to think about providing placeholder info that doesn't make the user erroneously think they must conform to a particular format (e.g., a username _must_ be in the format of first letter of first name then last name)

**Comment by sarahemm** [comment]
Just saw your comments after putting the PR in, oops :) Happy to change it if you think of something that doesn't imply format. I thought about just 'username' and 'nickname' but that seems silly I think.
